#!/bin/sh

# Reference:
# http://www.arduino.cc/playground/Interfacing/LinuxTTY

DEV=$1
if ! [ -e "$DEV" ] ; then
  echo "not a file: $DEV"
  exit 1
fi

BWD="9600"

stty -F "$DEV" cs8 $BWD ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts

cat "$DEV"
