#!/bin/sh

# Reference:
# http://www.arduino.cc/playground/Interfacing/LinuxTTY

BWD="9600"

tryCat () {
  DEV=$1
  if ! [ -e "$DEV" ] ; then
    echo "not a file: $DEV"
    return 1
  fi

  stty -F "$DEV" cs8 $BWD ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
  cat "$DEV"
  echo "disconnected."
}

while true; do
  tryCat $*
  sleep 5
done
